
[rule]
author = ["Liane Mulvaney"]
description = "Detects .bat file extensions on any dest port that isn't port 80 using Zeek HTTP data"
from = "now-6m" 
name = "Bat files observed in HTTP traffic on unusual port"
risk_score = 27
severity = "low"
type = "query"
rule_id = "0001"
query = '''
event.dataset: "zeek.http" and url.extension: txt and not destination.port: 80
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[rule.threat.technique.subtechnique]]
id = "T1059.003"
name = "Windows Command Shell"
reference = "https://attack.mitre.org/techniques/T1059/003/"

[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"

