
[rule]
author = ["Liane Mulvaney"]
description = "Using sysmon data, we're triggering on Powershell logs where Invoke-WebRequest and .bat strings are observed"
from = "now-6m" 
name = "Powershell Invoke-WebRequest Downloading .BAT file"
risk_score = 21
severity = "low"
tags = ["Example", "Tag"]
type = "query"
rule_id = "0005"
query = '''
event.dataset: "windows.sysmon_operational" and process.parent.name: powershell.exe and process.parent.command_line : *Invoke-WebRequest* and process.command_line: *.bat*
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1046/"
[[rule.threat.technique.subtechnique]]
id = "T1059.001"
name = "PowerShell"
reference = "https://attack.mitre.org/techniques/T1059/001/"

[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"


