
[rule]
author = ["Liane Mulvaney"]
description = "Detects Nmap and Nikto User Agent Strings"
from = "now-6m" 
name = "Web Scanner Activity Nmap and Nikto"
risk_score = 22
severity = "low"
type = "query"
rule_id = "0006"
query = '''
event.dataset: zeek.http and user_agent.original: *Nmap* or user_agent.original: *Nikto*
'''


[[rule.threat]] # Example Tactic, Technique, sub-Technique
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1046"
name = "Network Service Discovery"
reference = "https://attack.mitre.org/techniques/T1046/"

[rule.threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"

