name: Updating Detections


on:
  push:
    - '**.toml'
  workflow_dispatch:

jobs:
  elastic-detections-update:
    runs-on: ubuntu-latest
    env:
      ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
       name: Get changed files
       id: changed-files
       uses: tj-actions/changed-files@v44


      - name: List all changed files
        env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
          done
     